/// Common Pakistani banks for payout / bank-transfer selection.
const List<String> kPakistaniBanks = [
  'Meezan Bank',
  'Allied Bank (ABL)',
  'Habib Bank (HBL)',
  'United Bank (UBL)',
  'MCB Bank',
  'National Bank (NBP)',
  'Bank Alfalah',
  'Faysal Bank',
  'Askari Bank',
  'Bank of Punjab (BOP)',
  'JS Bank',
  'Soneri Bank',
  'Standard Chartered',
  'Dubai Islamic Bank',
  'BankIslami',
  'Al Baraka Bank',
  'Habib Metropolitan Bank',
  'Sindh Bank',
  'Silkbank',
  'Samba Bank',
  'First Women Bank',
  'Summit Bank',
];
